### ISSUE TITLE
Add VSCodium support 

### ISSUE THREAD

**Issue by Th0m4** [tclaude94/VSCodeGithub#2]
Hi, 
I don't know how to do a pull requests (and I'm scared of breaking everything),  so I fork your project and add VSCodium support.

**Comment by thclaude** [comment]
Hi,

You can check this to create the PR : [Creating a pull request from a fork](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork).

And don't be scared, we will settle any conflicts (if any) in the PR 👌.

I'm pretty busy lately, so I'll take a look at your PR asap.

**Comment by Th0m4** [comment]
Thanks ! 

No problem take a look when you have time !
